{% set name = "ipytree" %}
{% set version = "0.1.5" %}
{% set sha256 = "ed16577c1b74d6ea43724a39efaacce9679876da32cfedef8cec5fe6b934a933" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - ipywidgets >=7.5.0,<8.0.0

test:
  imports:
    - ipytree

about:
  home: http://github.com/QuantStack/ipytree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Jupyter Notebook Tree Widget using jsTree'
  dev_url: https://github.com/QuantStack/ipytree

extra:
  recipe-maintainers:
    - martinRenou
