travis:
  secure:
    BINSTAR_TOKEN: Tau9QWt/gUuScnOH2X/enqexPK8s5Dok7chuszeZStl/TMsoj/CU0st+YA6A6qPaaJFXrU9kDYh0x7FoNiHzX/s+Zg/KEdNcOc9t7GBTyBNUxAgQqyX9bN2gb+jcqu4vjO+KYRxoxKFP5mtgS/rbKXn3nY1mlLHZTV118Tb6090KbVuerjLCevPo4ZXbSaPKzjdSgWoMDgBuFw78GeplyGIQplFQCWJ8gNIKwyXa+FsB9fa4yObKUivG1QJ6ku1+sj5NKLbdHZNouJzlqcwLN6U+Qwc4tyaCVFhFVUbkfdZQ92GuRk7zga4g+jR52M7BM5uWpxs1odilRcaRZKqw89Egq5Oyuf38RFfE+hwqgrtCVP+Easm/rpud9OX7zDiC4fPkqSKmtUEvSylg/Ioz882vrTacx1u5K9pbXLPVmfDlm3dmjMWxoz+3aLvhI98J5oxb3uLRvRlejii0AaFMwBFI85ELkurUjqmQK84UjdAEFmYW8qucvyi5bIKFOQ6VT4JLi0AOYOUl806c0Oo+XduGMH0gXXSMCD4dbFZBYxWXfxpihOLpE9nBlauookgAaPwfCr3oI2AKcnqz20q9KtbASrWl1J5lH900Eld2j2FyJw6mQ8qkaf854a/V9A1Fovsf0gNOqpQ3MdL+XVslPTmB3v96wON3b1Usdgo/pfI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
